"""Regenerate ``requirements.lock.txt`` — the hash-locked, resolver-free install.

``uv.lock`` already pins every version, but only ``uv`` can read it, and a
consumer installing causalab into an existing environment (a cluster job image,
a colleague's venv, a reviewer reproducing a number) has neither ``uv`` nor a
reason to let a resolver pick anything. What that consumer needs is the thing
this script writes: every dependency pinned with ``==``, every artifact named by
its SHA-256, and no resolution step at all.

The one command, in one place. CI regenerates and diffs, `docs/standalone_install.md`
quotes the install line, and `tests/test_requirements_lock.py` checks the
file's shape — so there is a single definition of what the lock is and three
readers of it, rather than three commands that agree until they don't. That is
the same treatment ``uv.lock`` already gets.

**What is and is not in it.**

* ``--no-dev`` — the dev and lint groups are the repo's own tooling, not a
  consumer's dependencies.
* ``--no-emit-project`` — causalab itself is deliberately absent. Emitting it
  would write a *local path*, which is exactly what a standalone consumer
  cannot use; they install the wheel with ``--no-deps`` alongside this file.
  See the recipe in the docs.
* **no extras.** ``notebook`` is a jupyter-server stack a headless install has
  no use for, and ``nnsight`` is a **git** dependency — a git revision has no
  artifact hash, so including it would make ``--require-hashes`` impossible for
  everyone. The optional ``flash-attn`` and ``flash-linear-attention`` GPU
  stacks also stay out, keeping the base install on Transformers' fallbacks.

**The export is universal, not per-platform.** ``uv export`` emits the
lockfile's full marker set, so the linux ``nvidia-cu12`` wheels and win32
``colorama`` appear with their markers and the file is byte-identical whatever
machine writes it. That is what makes the CI diff a real check rather than a
guarantee of failure on a different runner.

Usage::

    # Rewrite requirements.lock.txt in place.
    uv run python scripts/export_requirements_lock.py

    # Say whether it is stale, write nothing, exit 1 if it is.
    uv run python scripts/export_requirements_lock.py --check
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LOCK = REPO / "requirements.lock.txt"

#: The export, as a fixed argument list. ``--frozen`` is load-bearing: without
#: it ``uv`` may re-resolve and silently write a lock that ``uv.lock`` does not
#: describe, which would make this file a second, disagreeing source of pins.
#: ``--color never`` is not cosmetic: ``uv`` colours the comment lines it emits
#: even when stdout is a pipe, so without it the committed file carries ~450 ANSI
#: escapes — invisible in a terminal, and a ``pip`` parse error for the consumer
#: this file exists to serve. ``test_requirements_lock`` asserts there are none.
COMMAND: tuple[str, ...] = (
    "uv",
    "export",
    "--frozen",
    "--no-dev",
    "--no-emit-project",
    "--format",
    "requirements-txt",
    "--hashes",
    "--color",
    "never",
)

#: Written above the export so a reader of the file knows how to regenerate it
#: without going looking. ``uv``'s own header names the raw command including
#: whatever ``-o`` path it was given, which is machine-specific — this names the
#: script instead.
HEADER = (
    "# Generated by scripts/export_requirements_lock.py — do not hand-edit.\n"
    "# Regenerate with: uv run python scripts/export_requirements_lock.py\n"
    "# CI fails on a diff, exactly as it does for uv.lock.\n"
)


def export() -> str:
    """The lock file's content, as ``uv`` produces it today."""
    result = subprocess.run(
        COMMAND, cwd=REPO, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise SystemExit(
            f"{' '.join(COMMAND)} failed with exit {result.returncode}:\n"
            f"{result.stderr}"
        )
    return HEADER + result.stdout


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if the lock is stale",
    )
    args = parser.parse_args(argv)

    # The lock is UTF-8 by construction (its header carries an em dash), so it
    # is read and written as UTF-8 by name rather than by whatever the locale
    # says: under `LC_ALL=C` with UTF-8 mode off, Python's default is ASCII and
    # `--check` would raise on the committed file instead of reporting. The
    # report goes to stdout as UTF-8 for the same reason — a diff of a UTF-8
    # file is UTF-8 text, whatever the terminal's locale.
    sys.stdout.reconfigure(encoding="utf-8")
    want = export()
    have = LOCK.read_text(encoding="utf-8") if LOCK.exists() else ""
    if want == have:
        print(f"{LOCK.name} is current")
        return 0
    if not args.check:
        LOCK.write_text(want, encoding="utf-8")
        print(f"wrote {LOCK.name}")
        return 0
    diff = difflib.unified_diff(
        have.splitlines(keepends=True),
        want.splitlines(keepends=True),
        fromfile=f"{LOCK.name} (committed)",
        tofile=f"{LOCK.name} (regenerated)",
        n=1,
    )
    sys.stdout.writelines(diff)
    print(
        f"\n{LOCK.name} is stale — run "
        "`uv run python scripts/export_requirements_lock.py`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
